### ISSUE TITLE
21.03.15 daily scrum

### ISSUE THREAD

**Issue by UKDuckbill** [cheonlian/DeepfakeBlock#18]
![image](https://user-images.githubusercontent.com/24719984/111166830-e02c4480-85e3-11eb-851f-8771876110f3.png)

**Comment by UKDuckbill** [comment]
## Achieve.
- 캐글 공부
- Shadow Attack 적용 모델 제작(실패)
## Plan.
- Shadow Attack의 채널 시스템 분석
## Obstacle.
- Shadow Attack.. 꼭 뭔갈 해보고 싶다..

**Comment by Doheon** [comment]
## Achieve
웹 수정사항 수정  
일단 최종 완성

## Plan
TOG논문 읽기 시도  
faceswap 적용 시도
hyper parameter tunning

## Obstacle
TOG를 이해하기 힘들다.

**Comment by hughqlee** [comment]
## Achieve.
Research YOLOv3 detector.
## Plan.
Research TOG attacks.
## Obstacle.
None.

**Comment by hojp7874** [comment]
## Achieve
- 발표 ppt작성
## Plan
- 중간발표 모델 검증
## Obstacle
-
